### ISSUE TITLE
Функция бана

### ISSUE THREAD

**Issue by Gzblizz** [Nsnk-hue/TwitchBot-via-TwitchLib#1]
Привет, не думал попробовать разработать команду(функцию) бана ботов?
Не просто плохие слова а именно в чат налетело 20+ ботов с одинаковым сообщением, и по одной команде на пример
!banp (кусок сообщения)
И после этого проходила проверка прошлых сообщений и если находил сходства улетали в бан.

**Comment by Nsnk-hue** [comment]
> Привет, не думал попробовать разработать команду(функцию) бана ботов?
> Не просто плохие слова а именно в чат налетело 20+ ботов с одинаковым сообщением, и по одной команде на пример
> !banp (кусок сообщения)
> И после этого проходила проверка прошлых сообщений и если находил сходства улетали в бан.

Привет!
Спасибо за идею, попробую реализовать (надеюсь получится).

**Comment by Gzblizz** [comment]
как успехи?

**Comment by Gzblizz** [comment]
получается не вышло?

**Comment by Nsnk-hue** [comment]
Да, не получилось.
